import { Plan } from '../types';

export const plans: Plan[] = [
    {
        name: 'Starter Plan',
        price: 'Rs.0',
        priceDetails: '/ month',
        features: [
            '10 image generations',
            '3 short videos',
            'Standard speed',
            'Watermark removed',
        ],
        bgColor: 'bg-slate-800',
        borderColor: 'border-slate-700',
        buttonColor: 'bg-sky-500',
        buttonTextColor: 'text-white',
        imageLimit: 10,
        videoLimit: 3,
    },
    {
        name: 'Pro Plan',
        price: 'Rs.999',
        priceDetails: '/ month (≈ $4.99)',
        features: [
            '25 image generations',
            '7 videos',
            'Fast processing',
            'No watermark + HD quality',
            'Commercial use license',
        ],
        bgColor: 'bg-slate-800',
        borderColor: 'border-sky-500',
        buttonColor: 'bg-sky-500',
        buttonTextColor: 'text-white',
        highlight: true,
        highlightText: 'Most Popular',
        imageLimit: 25,
        videoLimit: 7,
    },
    {
        name: 'Super Pro Plan',
        price: 'Rs.2,999',
        priceDetails: '/ month (≈ $14.99)',
        features: [
            '50 images',
            '12 videos',
            'HD + 4K output',
            'Commercial use license',
            'Early access to new AI features',
        ],
        bgColor: 'bg-slate-800',
        borderColor: 'border-slate-700',
        buttonColor: 'bg-sky-500',
        buttonTextColor: 'text-white',
        imageLimit: 50,
        videoLimit: 12,
    },
    {
        name: 'Mega Pro Plan',
        price: 'Rs.4,999',
        priceDetails: '/ month (≈ $24.99)',
        features: [
            '100 images',
            '20 videos',
            '8K output',
            'Commercial use Unlimited license',
            'Early access to new AI features',
        ],
        bgColor: 'bg-slate-800',
        borderColor: 'border-slate-700',
        buttonColor: 'bg-sky-500',
        buttonTextColor: 'text-white',
        imageLimit: 100,
        videoLimit: 20,
    }
];
